choco install allway-sync
choco install atom
choco install ccleaner
choco install cheatengine
choco install driverbooster
choco install fileshredder
choco install firefox
choco install foxitreader
choco install gamebooster
choco install geforce-experience
choco install gimp
choco install git
choco install gitkraken
choco install googlechrome
choco install handbrake.install
choco install hearthstone-deck-tracker
choco install hearthstone-deck-tracker-arena-helper
choco install inkscape
choco install intellijidea-ultimate
choco install jre8
choco install logitech-options
choco install malwarebytes
choco install maven
choco install megasync
choco install notepadplusplus.install
choco install openhardwaremonitor
choco install pia
choco install postman
choco install putty.install
choco install pycharm
choco install python
choco install qbittorrent
choco install resilio-sync-home
choco install spotify
choco install steam
choco install teamviewer
choco install telegram.install
choco install vivaldi
choco install vlc
choco install whatsapp
choco install windirstat
choco install wireshark
