choco install allway-sync
choco install atom
choco install autohotkey.portable
choco install ccleaner
choco install cheatengine
choco install chocolatey
choco install chocolatey-core.extension
choco install chocolatey-windowsupdate.extension
choco install DotNet4.5.2
choco install DotNet4.6.1
choco install driverbooster
choco install fileshredder
choco install Firefox
choco install foxitreader
choco install gamebooster
choco install geforce-experience
choco install gimp
choco install git
choco install git.install
choco install gitkraken
choco install GoogleChrome
choco install handbrake.install
choco install hearthstone-deck-tracker
choco install hearthstone-deck-tracker-arena-helper
choco install hyper
choco install InkScape
choco install intellijidea-ultimate
choco install jdk8
choco install jdownloader
choco install jre8
choco install KB2919355
choco install KB2919442
choco install KB2999226
choco install KB3033929
choco install KB3035131
choco install logitech-options
choco install malwarebytes
choco install maven
choco install megasync
choco install mp3tag
choco install notepadplusplus.install
choco install openhardwaremonitor
choco install pia
choco install pip
choco install postman
choco install putty.install
choco install pycharm
choco install python
choco install python3
choco install qbittorrent
choco install resilio-sync-home
choco install skype
choco install spotify
choco install steam
choco install teamviewer
choco install telegram.install
choco install tomcat
choco install tor-browser
choco install vcredist140
choco install vcredist2015
choco install veeam-agent
choco install vivaldi
choco install vlc
choco install WhatsApp
choco install win32diskimager
choco install win32diskimager.install
choco install windirstat
choco install WinPcap
choco install winrar
choco install wireshark
