choco install 7zip
choco install allway-sync
choco install atom
choco install audacity
choco install battle.net
choco install ccleaner
choco install etcher
choco install driverbooster
choco install fileshredder
choco install firefox
choco install foxitreader
choco install gamebooster
choco install geforce-experience
choco install gimp
choco install git
choco install gitkraken
choco install googlechrome
choco install handbrake
choco install hearthstone-deck-tracker
choco install inkscape
choco install intellijidea-ultimate
choco install jdownloader
choco install jre8
choco install logitech-options
choco install malwarebytes
choco install maven
choco install megasync
choco install mp3tag
choco install notepadplusplus
choco install notepadplusplus.install
choco install pia
choco install postman
choco install putty
choco install pycharm
choco install python
choco install resilio-sync-home
choco install spotify
choco install steam
choco install teamspeak
choco install teamviewer
choco install telegram
choco install transmission
choco install vivaldi
choco install vlc
choco install whatsapp
choco install windirstat
choco install winrar
choco install wireshark
